/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.clb.ude.pb.Proyecto_De_Aula.vistas.MenusEstudiante;

import co.clb.ude.pb.Proyecto_De_Aula.entidades.Usuario;
import co.clb.ude.pb.Proyecto_De_Aula.vistas.LogIncomponentes.LogInEstudiante;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import org.eclipse.persistence.eis.EISException;

/**
 *
 * @author daniel
 */
public class PanelInfoEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form PanelInfoEstudiante
     */
    public PanelInfoEstudiante() {
        initComponents();
        configurarCamposTexto();
        grupoGenero();
        configurarDateChooser();

        //String name = LogInEstudiante.usuario.getNombres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesGenero = new javax.swing.ButtonGroup();
        SignUpTxt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        nombreEstTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        correoEstTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelCorrreo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelContraseña = new javax.swing.JLabel();
        nuevaContraseñaEstTxt = new javax.swing.JPasswordField();
        SignUpBoton = new javax.swing.JPanel();
        ActualizarTxt = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        apellidoEstTxt = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelConfirmarContraseña = new javax.swing.JLabel();
        confirmarContraseñaEstTxt = new javax.swing.JPasswordField();
        jLabelID = new javax.swing.JLabel();
        IDEstTxt = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        gMujer = new javax.swing.JRadioButton();
        gHombre = new javax.swing.JRadioButton();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jDateChooserEst = new com.toedter.calendar.JDateChooser();
        jLabelTelefono = new javax.swing.JLabel();
        TelefonoEstTxt = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabelCodigoEstudiante = new javax.swing.JLabel();
        CodigoEstTxt = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabelGrupo = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabelSemestre = new javax.swing.JLabel();
        SemestreEstTxt = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        SignUpBoton1 = new javax.swing.JPanel();
        SignUpTxt2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        SignUpTxt.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        SignUpTxt.setForeground(new java.awt.Color(255, 255, 255));
        SignUpTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpTxt.setText("modificar");
        SignUpTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        SignUpTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpTxtMouseExited(evt);
            }
        });

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNombre.setText("Nombre(s)");
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 30));

        nombreEstTxt.setForeground(new java.awt.Color(204, 204, 204));
        nombreEstTxt.setText("Ingrese su(s) Nombre(s)");
        nombreEstTxt.setBorder(null);
        nombreEstTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreEstTxtMousePressed(evt);
            }
        });
        nombreEstTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEstTxtActionPerformed(evt);
            }
        });
        jPanel1.add(nombreEstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 170, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 170, -1));

        correoEstTxt.setForeground(new java.awt.Color(204, 204, 204));
        correoEstTxt.setText("Ingrese su correo");
        correoEstTxt.setBorder(null);
        correoEstTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correoEstTxtMousePressed(evt);
            }
        });
        correoEstTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoEstTxtActionPerformed(evt);
            }
        });
        jPanel1.add(correoEstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 160, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 160, -1));

        jLabelCorrreo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelCorrreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCorrreo.setText("Correo");
        jPanel1.add(jLabelCorrreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 160, -1));

        jLabelContraseña.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelContraseña.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelContraseña.setText("Nueva Contraseña");
        jPanel1.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 100, 30));

        nuevaContraseñaEstTxt.setForeground(new java.awt.Color(204, 204, 204));
        nuevaContraseñaEstTxt.setText("jPasswordField1");
        nuevaContraseñaEstTxt.setBorder(null);
        nuevaContraseñaEstTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nuevaContraseñaEstTxtMousePressed(evt);
            }
        });
        nuevaContraseñaEstTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaContraseñaEstTxtActionPerformed(evt);
            }
        });
        jPanel1.add(nuevaContraseñaEstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 160, 30));

        SignUpBoton.setBackground(new java.awt.Color(1, 174, 250));

        ActualizarTxt.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        ActualizarTxt.setForeground(new java.awt.Color(255, 255, 255));
        ActualizarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActualizarTxt.setText("Actualizar");
        ActualizarTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ActualizarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActualizarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActualizarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActualizarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SignUpBotonLayout = new javax.swing.GroupLayout(SignUpBoton);
        SignUpBoton.setLayout(SignUpBotonLayout);
        SignUpBotonLayout.setHorizontalGroup(
            SignUpBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpBotonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ActualizarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SignUpBotonLayout.setVerticalGroup(
            SignUpBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpBotonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ActualizarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(SignUpBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, 30));

        jLabelApellido.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelApellido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelApellido.setText("Apellido(s)");
        jPanel1.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 130, 30));

        apellidoEstTxt.setForeground(new java.awt.Color(204, 204, 204));
        apellidoEstTxt.setText("Ingrese su(s) Apellido(s)");
        apellidoEstTxt.setBorder(null);
        apellidoEstTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apellidoEstTxtMousePressed(evt);
            }
        });
        apellidoEstTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoEstTxtActionPerformed(evt);
            }
        });
        jPanel1.add(apellidoEstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 170, 30));

        jLabelGenero.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelGenero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelGenero.setText("Genero");
        jPanel1.add(jLabelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 130, 30));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 170, 10));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 170, -1));

        jLabelConfirmarContraseña.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelConfirmarContraseña.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelConfirmarContraseña.setText("Confirmar Contraseña");
        jPanel1.add(jLabelConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 120, 30));

        confirmarContraseñaEstTxt.setForeground(new java.awt.Color(204, 204, 204));
        confirmarContraseñaEstTxt.setText("jPasswordField1");
        confirmarContraseñaEstTxt.setBorder(null);
        confirmarContraseñaEstTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmarContraseñaEstTxtMousePressed(evt);
            }
        });
        confirmarContraseñaEstTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarContraseñaEstTxtActionPerformed(evt);
            }
        });
        jPanel1.add(confirmarContraseñaEstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 170, 30));

        jLabelID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelID.setText("ID");
        jPanel1.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 130, 30));

        IDEstTxt.setForeground(new java.awt.Color(204, 204, 204));
        IDEstTxt.setText("Numero de Identificacion");
        IDEstTxt.setBorder(null);
        IDEstTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IDEstTxtMousePressed(evt);
            }
        });
        IDEstTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEstTxtActionPerformed(evt);
            }
        });
        jPanel1.add(IDEstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 170, 30));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 170, -1));

        gMujer.setText("Mujer");
        gMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gMujerActionPerformed(evt);
            }
        });
        jPanel1.add(gMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 80, 30));

        gHombre.setText("Hombre");
        gHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gHombreActionPerformed(evt);
            }
        });
        jPanel1.add(gHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 80, 30));

        jLabelFechaNacimiento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelFechaNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFechaNacimiento.setText("Fecha de nacimiento");
        jPanel1.add(jLabelFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 130, 30));

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 170, -1));

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 170, 10));
        jPanel1.add(jDateChooserEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 170, 30));

        jLabelTelefono.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTelefono.setText("Telefono");
        jPanel1.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 130, 30));

        TelefonoEstTxt.setForeground(new java.awt.Color(204, 204, 204));
        TelefonoEstTxt.setText("Ingrese se numero de Telefono");
        TelefonoEstTxt.setBorder(null);
        TelefonoEstTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelefonoEstTxtMousePressed(evt);
            }
        });
        TelefonoEstTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoEstTxtActionPerformed(evt);
            }
        });
        jPanel1.add(TelefonoEstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 170, 30));

        jSeparator10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 170, -1));

        jLabelCodigoEstudiante.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelCodigoEstudiante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCodigoEstudiante.setText("Codigo Estudiante");
        jPanel1.add(jLabelCodigoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 140, 30));

        CodigoEstTxt.setForeground(new java.awt.Color(204, 204, 204));
        CodigoEstTxt.setBorder(null);
        CodigoEstTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CodigoEstTxtMousePressed(evt);
            }
        });
        CodigoEstTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoEstTxtActionPerformed(evt);
            }
        });
        jPanel1.add(CodigoEstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 180, 30));

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 180, 10));

        jLabelGrupo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelGrupo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelGrupo.setText("Carrera");
        jPanel1.add(jLabelGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 130, 30));

        jSeparator12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 170, 10));

        jLabelSemestre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabelSemestre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSemestre.setText("Semestre");
        jPanel1.add(jLabelSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 130, 30));

        SemestreEstTxt.setForeground(new java.awt.Color(204, 204, 204));
        SemestreEstTxt.setText("Ingrese el Semestre");
        SemestreEstTxt.setBorder(null);
        SemestreEstTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SemestreEstTxtMousePressed(evt);
            }
        });
        SemestreEstTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemestreEstTxtActionPerformed(evt);
            }
        });
        jPanel1.add(SemestreEstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 170, 30));

        jSeparator13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 170, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione una carrera", "Ingeneria en sistemas", "Ingeneria industrial", "Ingeneria quimica", "licenciatura en bilinguismo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 170, 30));

        SignUpBoton1.setBackground(new java.awt.Color(1, 174, 250));

        SignUpTxt2.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        SignUpTxt2.setForeground(new java.awt.Color(255, 255, 255));
        SignUpTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpTxt2.setText("Modificar");
        SignUpTxt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        SignUpTxt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpTxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpTxt2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpTxt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpTxt2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout SignUpBoton1Layout = new javax.swing.GroupLayout(SignUpBoton1);
        SignUpBoton1.setLayout(SignUpBoton1Layout);
        SignUpBoton1Layout.setHorizontalGroup(
            SignUpBoton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpTxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );
        SignUpBoton1Layout.setVerticalGroup(
            SignUpBoton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(SignUpBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 30));

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Debe confirmar su codigo ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 150, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void nombreEstTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreEstTxtMousePressed
        if (nombreEstTxt.getText().equals("Ingrese su(s) Nombre(s)")) {
            nombreEstTxt.setText("");
            nombreEstTxt.setForeground(Color.black);
        }

        restaurarTextoPredeterminado();
    }//GEN-LAST:event_nombreEstTxtMousePressed

    private void nombreEstTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEstTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEstTxtActionPerformed

    private void correoEstTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoEstTxtMousePressed
        if (correoEstTxt.getText().equals("Ingrese su correo")) {
            correoEstTxt.setText("");
            correoEstTxt.setForeground(Color.black);
        }

        restaurarTextoPredeterminado();
    }//GEN-LAST:event_correoEstTxtMousePressed

    private void correoEstTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoEstTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoEstTxtActionPerformed

    private void nuevaContraseñaEstTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaContraseñaEstTxtMousePressed
        if (String.valueOf(nuevaContraseñaEstTxt.getPassword()).equals("•••••••••••••••")) {
            nuevaContraseñaEstTxt.setText("");
            nuevaContraseñaEstTxt.setForeground(Color.black);
        }

        restaurarTextoPredeterminado();
    }//GEN-LAST:event_nuevaContraseñaEstTxtMousePressed

    private void nuevaContraseñaEstTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaContraseñaEstTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevaContraseñaEstTxtActionPerformed

    private void SignUpTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTxtMouseClicked
        if (!validarEntrada()) {
            return;
        } else {
            JOptionPane.showMessageDialog(null, "Información modificada correctamente");
        }

    }//GEN-LAST:event_SignUpTxtMouseClicked

    private void SignUpTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTxtMouseEntered
        SignUpBoton.setBackground(new Color(1, 105, 150));
    }//GEN-LAST:event_SignUpTxtMouseEntered

    private void SignUpTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTxtMouseExited
        SignUpBoton.setBackground(new Color(1, 174, 250));
    }//GEN-LAST:event_SignUpTxtMouseExited

    private void apellidoEstTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellidoEstTxtMousePressed
        if (apellidoEstTxt.getText().equals("Ingrese su(s) Apellido(s)")) {
            apellidoEstTxt.setText("");
            apellidoEstTxt.setForeground(Color.black);
        }

        restaurarTextoPredeterminado();
    }//GEN-LAST:event_apellidoEstTxtMousePressed

    private void apellidoEstTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoEstTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoEstTxtActionPerformed

    private void confirmarContraseñaEstTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarContraseñaEstTxtMousePressed
        if (String.valueOf(confirmarContraseñaEstTxt.getPassword()).equals("•••••••••••••••")) {
            confirmarContraseñaEstTxt.setText("");
            confirmarContraseñaEstTxt.setForeground(Color.black);
        }

        restaurarTextoPredeterminado();
    }//GEN-LAST:event_confirmarContraseñaEstTxtMousePressed

    private void confirmarContraseñaEstTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarContraseñaEstTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarContraseñaEstTxtActionPerformed

    private void IDEstTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDEstTxtMousePressed
        if (IDEstTxt.getText().equals("Numero de Identificacion")) {
            IDEstTxt.setText("");
            IDEstTxt.setForeground(Color.black);
        }

        restaurarTextoPredeterminado();
    }//GEN-LAST:event_IDEstTxtMousePressed

    private void IDEstTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEstTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEstTxtActionPerformed

    private void gMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gMujerActionPerformed

    private void gHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gHombreActionPerformed

    private void TelefonoEstTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelefonoEstTxtMousePressed
        if (TelefonoEstTxt.getText().equals("Numero de Identificacion")) {
            TelefonoEstTxt.setText("");
            TelefonoEstTxt.setForeground(Color.black);
        }

        restaurarTextoPredeterminado();
    }//GEN-LAST:event_TelefonoEstTxtMousePressed

    private void TelefonoEstTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoEstTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoEstTxtActionPerformed

    private void CodigoEstTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodigoEstTxtMousePressed
        if (CodigoEstTxt.getText().equals("Numero de Identificacion")) {
            CodigoEstTxt.setText("");
            CodigoEstTxt.setForeground(Color.black);
        }

        restaurarTextoPredeterminado();
    }//GEN-LAST:event_CodigoEstTxtMousePressed

    private void CodigoEstTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoEstTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoEstTxtActionPerformed

    private void SemestreEstTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SemestreEstTxtMousePressed
        if (SemestreEstTxt.getText().equals("Numero de Identificacion")) {
            SemestreEstTxt.setText("");
            SemestreEstTxt.setForeground(Color.black);
        }

        restaurarTextoPredeterminado();
    }//GEN-LAST:event_SemestreEstTxtMousePressed

    private void SemestreEstTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemestreEstTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemestreEstTxtActionPerformed

    private void ActualizarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarTxtMouseClicked
        
       botonactualizar();
    }//GEN-LAST:event_ActualizarTxtMouseClicked

    private void ActualizarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarTxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarTxtMouseEntered

    private void ActualizarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarTxtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarTxtMouseExited

    private void SignUpTxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTxt2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpTxt2MouseClicked

    private void SignUpTxt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTxt2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpTxt2MouseEntered

    private void SignUpTxt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTxt2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpTxt2MouseExited

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void configurarDateChooser() {
        jDateChooserEst.setDateFormatString("d/MM/yyyy");
        jDateChooserEst.getDateEditor().setEnabled(false);
        jDateChooserEst.setSelectableDateRange(new java.util.Date(0), new java.util.Date()); // permite seleccionar fechas hasta la fecha actual
    }

    private void grupoGenero() {
        botonesGenero = new ButtonGroup();
        botonesGenero.add(gHombre);
        botonesGenero.add(gMujer);
    }

    private void configurarCamposTexto() {
        IDEstTxt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (!Character.isDigit(caracter)) {
                    e.consume();
                }
            }
        });

        nombreEstTxt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (!Character.isLetter(caracter) && !Character.isWhitespace(caracter)) {
                    e.consume();
                }
            }
        });

        apellidoEstTxt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (!Character.isLetter(caracter) && !Character.isWhitespace(caracter)) {
                    e.consume();
                }
            }
        });

        TelefonoEstTxt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (!Character.isDigit(caracter)) {
                    e.consume();
                }
            }
        });

        SemestreEstTxt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                if (!Character.isDigit(caracter)) {
                    e.consume();
                }
            }
        });

        TextosPredeterminado(nombreEstTxt, "Ingrese su(s) Nombre(s)");
        TextosPredeterminado(apellidoEstTxt, "Ingrese su(s) Apellido(s)");
        TextosPredeterminado(correoEstTxt, "Ingrese su correo");
        TextosPredeterminado(nuevaContraseñaEstTxt, "•••••••••••••••");
        TextosPredeterminado(confirmarContraseñaEstTxt, "•••••••••••••••");
        TextosPredeterminado(IDEstTxt, "Numero de Identificacion");
        TextosPredeterminado(TelefonoEstTxt, "Ingrese se numero de Telefono");
        TextosPredeterminado(SemestreEstTxt, "Ingrese el Semestre");

        agregarFocusListener(nombreEstTxt, "Ingrese su(s) Nombre(s)");
        agregarFocusListener(apellidoEstTxt, "Ingrese su(s) Apellido(s)");
        agregarFocusListener(correoEstTxt, "Ingrese su correo");
        agregarFocusListener(nuevaContraseñaEstTxt, "•••••••••••••••");
        agregarFocusListener(confirmarContraseñaEstTxt, "•••••••••••••••");
        agregarFocusListener(IDEstTxt, "Numero de Identificacion");
        agregarFocusListener(TelefonoEstTxt, "Ingrese se numero de Telefono");
        agregarFocusListener(SemestreEstTxt, "Ingrese el Semestre");
    }

    private void TextosPredeterminado(javax.swing.JTextField campo, String texto) {
        campo.setForeground(Color.gray);
        campo.setText(texto);
    }

    private void agregarFocusListener(javax.swing.JTextField campo, String texto) {
        campo.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (campo.getText().equals(texto)) {
                    campo.setText("");
                    campo.setForeground(Color.black);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(texto);
                    campo.setForeground(Color.gray);
                }
            }
        });
    }

    private void limpiarCampos() {
        TextosPredeterminado(nombreEstTxt, "Ingrese su(s) Nombre(s)");
        TextosPredeterminado(apellidoEstTxt, "Ingrese su(s) Apellido(s)");
        TextosPredeterminado(correoEstTxt, "Ingrese su correo");
        TextosPredeterminado(nuevaContraseñaEstTxt, "•••••••••••••••");
        TextosPredeterminado(confirmarContraseñaEstTxt, "•••••••••••••••");
        TextosPredeterminado(IDEstTxt, "Numero de Identificacion");
        TextosPredeterminado(TelefonoEstTxt, "Ingrese se numero de Telefono");
        TextosPredeterminado(SemestreEstTxt, "Ingrese el Semestre");
        botonesGenero.clearSelection();

        if (jDateChooserEst != null) {
            JTextFieldDateEditor editor = (JTextFieldDateEditor) jDateChooserEst.getDateEditor();
            editor.setText("dd/mm/yyyy");
            editor.setForeground(Color.gray);
            jDateChooserEst.setDate(null);
        }
    }

    private void restaurarTextoPredeterminado() {
        if (nombreEstTxt.getText().isEmpty()) {
            TextosPredeterminado(nombreEstTxt, "Ingrese su(s) Nombre(s)");
        }
        if (apellidoEstTxt.getText().isEmpty()) {
            TextosPredeterminado(apellidoEstTxt, "Ingrese su(s) Apellido(s)");
        }
        if (correoEstTxt.getText().isEmpty()) {
            TextosPredeterminado(correoEstTxt, "Ingrese su correo");
        }
        if (String.valueOf(nuevaContraseñaEstTxt.getPassword()).isEmpty()) {
            TextosPredeterminado(nuevaContraseñaEstTxt, "•••••••••••••••");
        }
        if (String.valueOf(confirmarContraseñaEstTxt.getPassword()).isEmpty()) {
            TextosPredeterminado(confirmarContraseñaEstTxt, "•••••••••••••••");
        }
        if (IDEstTxt.getText().isEmpty()) {
            TextosPredeterminado(IDEstTxt, "Numero de Identificacion");
        }
        if (TelefonoEstTxt.getText().isEmpty()) {
            TextosPredeterminado(TelefonoEstTxt, "Ingrese se numero de Telefono");
        }
        if (SemestreEstTxt.getText().isEmpty()) {
            TextosPredeterminado(SemestreEstTxt, "Ingrese el Semestre");
        }

        if (jDateChooserEst.getDate() == null) {
            JTextFieldDateEditor editor = (JTextFieldDateEditor) jDateChooserEst.getDateEditor();
            editor.setText("dd/mm/yyyy");
            editor.setForeground(Color.gray);
        }
    }

    // Fin de metodos visuales
    private class ValidacionContrseña {

        public static boolean contraseñasCoinciden(String contraseña, String confirmarContraseña) {
            return contraseña.equals(confirmarContraseña);
        }
    }

    private class ValidadorJDateChooser {

        public static boolean esFechaValida(JDateChooser jDateChooser) {
            if (jDateChooser.getDate() == null) {
                return false;
            }

            java.util.Date fechaNacimiento = jDateChooser.getDate();
            java.util.Calendar calNacimiento = java.util.Calendar.getInstance();
            calNacimiento.setTime(fechaNacimiento);

            java.util.Calendar calActual = java.util.Calendar.getInstance();

            int edad = calActual.get(java.util.Calendar.YEAR) - calNacimiento.get(java.util.Calendar.YEAR);
            int mesActual = calActual.get(java.util.Calendar.MONTH);
            int mesNacimiento = calNacimiento.get(java.util.Calendar.MONTH);
            int diaActual = calActual.get(java.util.Calendar.DAY_OF_MONTH);
            int diaNacimiento = calNacimiento.get(java.util.Calendar.DAY_OF_MONTH);

            if (mesNacimiento > mesActual || (mesNacimiento == mesActual && diaNacimiento > diaActual)) {
                edad--;
            }

            int edadMinima = 14;
            int edadMaxima = 100;

            return (edad >= edadMinima && edad <= edadMaxima);
        }
    }

    private static boolean esCorreoValido(String correoElectronico) {
        String patron = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(patron);
        Matcher matcher = pattern.matcher(correoElectronico);
        return matcher.matches();
    }

    private boolean validarGenero() {
        return gHombre.isSelected() || gMujer.isSelected();
    }

    private boolean validarEntrada() {
        if (!ValidadorJDateChooser.esFechaValida(jDateChooserEst)) {
            javax.swing.JOptionPane.showMessageDialog(jPanel1, "Debe seleccionar una fecha valida", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!validarGenero()) {
            javax.swing.JOptionPane.showMessageDialog(jPanel1, "Debe seleccionar su genero", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validar que el ID sea de 10 dígitos
        if (IDEstTxt.getText().trim().length() != 8 && IDEstTxt.getText().trim().length() != 10 && IDEstTxt.getText().trim().length() != 11) {
            javax.swing.JOptionPane.showMessageDialog(jPanel1, "Debe ingresar un numero de Identificacion valido", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validar que la contraseña tenga al menos 6 caracteres
        if (String.valueOf(nuevaContraseñaEstTxt.getPassword()).trim().length() < 6) {
            javax.swing.JOptionPane.showMessageDialog(jPanel1, "Debe ingresar una contraseña más larga (al menos 6 caracteres)", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!esCorreoValido(correoEstTxt.getText())) {
            javax.swing.JOptionPane.showMessageDialog(jPanel1, "Debe Ingresar un correo electrónico válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        String contraseña = String.valueOf(nuevaContraseñaEstTxt.getPassword());
        String confirmarContraseña = String.valueOf(confirmarContraseñaEstTxt.getPassword());

        if (!ValidacionContrseña.contraseñasCoinciden(contraseña, confirmarContraseña)) {
            javax.swing.JOptionPane.showMessageDialog(jPanel1, "Las contraseñas no coinciden", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (nombreEstTxt.getText().equals("Ingrese su(s) Nombre(s)")
                || apellidoEstTxt.getText().equals("Ingrese su(s) Apellido(s)")
                || correoEstTxt.getText().equals("Ingrese su correo")
                || String.valueOf(nuevaContraseñaEstTxt.getPassword()).equals("•••••••••••••••")
                || String.valueOf(confirmarContraseñaEstTxt.getPassword()).equals("•••••••••••••••")
                || IDEstTxt.getText().equals("Numero de Identificacion")
                || TelefonoEstTxt.getText().equals("Ingrese se numero de Telefono")
                || SemestreEstTxt.getText().equals("Ingrese el Semestre")) {

            javax.swing.JOptionPane.showMessageDialog(jPanel1, "Debe llenar todos los campos de informacion", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

            return false;
        }

        if (!ValidacionContrseña.contraseñasCoinciden(contraseña, confirmarContraseña)) {
            javax.swing.JOptionPane.showMessageDialog(jPanel1, "Las contraseñas no coinciden");
            return false;
        }

        return true;
    }

    private boolean botonactualizar() {
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/plataforma", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from estudiantes where  Codigo_Estudiante=?");
            pst.setString(1, CodigoEstTxt.getText().trim());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                nombreEstTxt.setText(rs.getString("Nombre"));
                apellidoEstTxt.setText(rs.getString("Apellido"));
                jDateChooserEst.setDate(rs.getDate("Nacimiento"));
                CodigoEstTxt.setText(rs.getString("Contraseña"));
                jComboBox1.setSelectedItem(rs.getString("Grupo"));

            } else {
                javax.swing.JOptionPane.showMessageDialog(jPanel1, "Alumno no escontrado", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
        return false;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualizarTxt;
    private javax.swing.JTextField CodigoEstTxt;
    private javax.swing.JTextField IDEstTxt;
    private javax.swing.JTextField SemestreEstTxt;
    private javax.swing.JPanel SignUpBoton;
    private javax.swing.JPanel SignUpBoton1;
    private javax.swing.JLabel SignUpTxt;
    private javax.swing.JLabel SignUpTxt2;
    private javax.swing.JTextField TelefonoEstTxt;
    private javax.swing.JTextField apellidoEstTxt;
    private javax.swing.ButtonGroup botonesGenero;
    private javax.swing.JPasswordField confirmarContraseñaEstTxt;
    private javax.swing.JTextField correoEstTxt;
    private javax.swing.JRadioButton gHombre;
    private javax.swing.JRadioButton gMujer;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooserEst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCodigoEstudiante;
    private javax.swing.JLabel jLabelConfirmarContraseña;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelCorrreo;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelGrupo;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSemestre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField nombreEstTxt;
    private javax.swing.JPasswordField nuevaContraseñaEstTxt;
    // End of variables declaration//GEN-END:variables
}
